code --install-extension akamud.vscode-theme-onedark
code --install-extension christian-kohler.path-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension dbaeumer.vscode-eslint
code --install-extension dunstontc.vscode-docker-syntax
code --install-extension EditorConfig.EditorConfig
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension FallenMax.mithril-emmet
code --install-extension Gajesh1.React-JS-Snippet
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension mrmlnc.vscode-duplicate
code --install-extension ms-vscode.atom-keybindings
code --install-extension ms-vscode.vscode-typescript-tslint-plugin
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension vscodevim.vim
code --install-extension WallabyJs.quokka-vscode
code --install-extension xabikos.ReactSnippets
